allowed-origins: "https://my-portfolios-gei.vercel.app,https://my-portfolios-*.vercel.app"

logging:
    level:
        org:
            hibernate: error
            springframework.core: error
            springframework.web: error
        root: error
